# Repository ruleset for the main branch
name: Main Branch Protection
target: branch
conditions:
  ref_name:
    include: [refs/heads/main, refs/heads/master]

rules:
  # Require pull request before merging
  pull_request:
    required: true
    dismiss_stale_reviews_on_push: true
    require_code_owner_review: true
    required_approving_review_count: 1

  # Require status checks to pass before merging
  required_status_checks:
    required: true
    strict: true
    contexts:
      - continuous-integration/github-actions/pr

  # Require linear history
  linear_history:
    required: true

  # Restrict push access to admins and maintainers
  creation: 
    requires: write

  # Protect against branch deletion
  deletion: 
    requires: admin

  # Require signed commits
  required_signatures:
    required: true

  # Restrict who can push to this branch
  push:
    requires: write

  # Enforce branch name patterns
  update:
    requires: write